name: Casino
main: DeadBush\Casino\main
api: [4.0.0]
version: 1.2
author: DeadBush

depend:
- "EconomyAPI"
commands:
  casino:
    permission: casino.use
    description: open casino menu!
permissions:
  casino.use:
    description: permission to give casino access
    default: true
